/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Answers sort parameter
 * @export
 */
export const AnswersSortParameter = {
    Score: 'score',
    Modified: 'modified',
    Creation: 'creation'
} as const;
export type AnswersSortParameter = typeof AnswersSortParameter[keyof typeof AnswersSortParameter];


export function instanceOfAnswersSortParameter(value: any): boolean {
    for (const key in AnswersSortParameter) {
        if (Object.prototype.hasOwnProperty.call(AnswersSortParameter, key)) {
            if (AnswersSortParameter[key as keyof typeof AnswersSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AnswersSortParameterFromJSON(json: any): AnswersSortParameter {
    return AnswersSortParameterFromJSONTyped(json, false);
}

export function AnswersSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswersSortParameter {
    return json as AnswersSortParameter;
}

export function AnswersSortParameterToJSON(value?: AnswersSortParameter | null): any {
    return value as any;
}

