/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * JSON representation of an answer request
 */
export type AnswerRequestModelJson = {
    body: string;
}

/**
 * 
 * @export
 * @interface AnswerRequestModel
 */
export interface AnswerRequestModel {
    /**
     * Answer body. The written content of the answer.
     * @type {string}
     * @memberof AnswerRequestModel
     */
    body: string;
}

/**
 * Check if a given object implements the AnswerRequestModel interface.
 */
export function instanceOfAnswerRequestModel(value: unknown): value is AnswerRequestModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<AnswerRequestModel>;
    return typeof v.body === 'string';
}

export function AnswerRequestModelFromJSON(json: AnswerRequestModelJson): AnswerRequestModel {
    return AnswerRequestModelFromJSONTyped(json, false);
}

export function AnswerRequestModelFromJSONTyped(
    json: AnswerRequestModelJson,
    ignoreDiscriminator: boolean
): AnswerRequestModel {
    if (!json) {
        throw new Error('AnswerRequestModel JSON cannot be null or undefined');
    }
    return {
        'body': json.body,
    };
}

export function AnswerRequestModelToJSON(value?: AnswerRequestModel | null): AnswerRequestModelJson | null {
    if (!value) {
        return null;
    }
    return {
        'body': value.body,
    };
}

