/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface AnswerSearchResultModel
 */
export interface AnswerSearchResultModel {
    /**
     * 
     * @type {string}
     * @memberof AnswerSearchResultModel
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof AnswerSearchResultModel
     */
    answerId?: number;
    /**
     * 
     * @type {number}
     * @memberof AnswerSearchResultModel
     */
    parentQuestionId?: number;
    /**
     * 
     * @type {string}
     * @memberof AnswerSearchResultModel
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof AnswerSearchResultModel
     */
    snippet?: string;
    /**
     * 
     * @type {Array<TagSummaryResponseModel>}
     * @memberof AnswerSearchResultModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof AnswerSearchResultModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {Date}
     * @memberof AnswerSearchResultModel
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the AnswerSearchResultModel interface.
 */
export function instanceOfAnswerSearchResultModel(value: object): value is AnswerSearchResultModel {
    return true;
}

export function AnswerSearchResultModelFromJSON(json: any): AnswerSearchResultModel {
    return AnswerSearchResultModelFromJSONTyped(json, false);
}

export function AnswerSearchResultModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): AnswerSearchResultModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'answerId': json['answerId'] == null ? undefined : json['answerId'],
        'parentQuestionId': json['parentQuestionId'] == null ? undefined : json['parentQuestionId'],
        'title': json['title'] == null ? undefined : json['title'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagSummaryResponseModelFromJSON)),
        'owner': json['owner'] == null ? undefined : UserSummaryResponseModelFromJSON(json['owner']),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

export function AnswerSearchResultModelToJSON(value?: AnswerSearchResultModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'answerId': value['answerId'],
        'parentQuestionId': value['parentQuestionId'],
        'title': value['title'],
        'snippet': value['snippet'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagSummaryResponseModelToJSON)),
        'owner': UserSummaryResponseModelToJSON(value['owner']),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

