/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticlePermissionsRequestModel, ArticlePermissionsRequestModelJson } from './ArticlePermissionsRequestModel';
import {
    ArticlePermissionsRequestModelFromJSON,
    ArticlePermissionsRequestModelFromJSONTyped,
    ArticlePermissionsRequestModelToJSON,
} from './ArticlePermissionsRequestModel';
import type { ArticleType } from './ArticleType';
import {
    ArticleTypeFromJSON,
    ArticleTypeFromJSONTyped,
    ArticleTypeToJSON,
} from './ArticleType';

/**
 * JSON representation of ArticleRequestModel
 */
export type ArticleRequestModelJson = {
    title: string;
    body: string;
    tags: string[];
    type: string;
    permissions: unknown;
}

/**
 * 
 * @export
 * @interface ArticleRequestModel
 */
export interface ArticleRequestModel {
    /**
     * Article title. The purpose of the article, stated briefly in one sentence.
     * @type {string}
     * @memberof ArticleRequestModel
     */
    title: string;
    /**
     * Body. The bulk of the information to share.
     * @type {string}
     * @memberof ArticleRequestModel
     */
    body: string;
    /**
     * Tags. Tags associated with the article.
     * @type {Array<string>}
     * @memberof ArticleRequestModel
     */
    tags: Array<string>;
    /**
     * 
     * @type {ArticleType}
     * @memberof ArticleRequestModel
     */
    type: ArticleType;
    /**
     * 
     * @type {ArticlePermissionsRequestModel}
     * @memberof ArticleRequestModel
     */
    permissions: ArticlePermissionsRequestModel;
}

/**
 * Check if a given object implements the ArticleRequestModel interface.
 */
export function instanceOfArticleRequestModel(value: unknown): value is ArticleRequestModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<ArticleRequestModel>;
    
    return typeof v.title === 'string' &&
           typeof v.body === 'string' &&
           Array.isArray(v.tags) &&
           v.tags.every(tag => typeof tag === 'string') &&
           v.type !== undefined &&
           v.permissions !== undefined;
}

export function ArticleRequestModelFromJSON(json: ArticleRequestModelJson): ArticleRequestModel {
    return ArticleRequestModelFromJSONTyped(json, false);
}

export function ArticleRequestModelFromJSONTyped(
    json: ArticleRequestModelJson,
    ignoreDiscriminator: boolean
): ArticleRequestModel {
    if (!json) {
        throw new Error('ArticleRequestModel JSON cannot be null or undefined');
    }
    
    return {
        'title': json['title'],
        'body': json['body'],
        'tags': Array.isArray(json['tags']) ? json['tags'] : [],
        'type': ArticleTypeFromJSON(json['type']),
        'permissions': ArticlePermissionsRequestModelFromJSON(json['permissions'] as ArticlePermissionsRequestModelJson),
    };
}

export function ArticleRequestModelToJSON(value?: ArticleRequestModel | null): ArticleRequestModelJson | null {
    if (!value) {
        return null;
    }
    
    const type = ArticleTypeToJSON(value.type);
    if (!type) {
        throw new Error('Invalid ArticleType value');
    }
    
    return {
        'title': value.title,
        'body': value.body,
        'tags': value.tags,
        'type': type,
        'permissions': ArticlePermissionsRequestModelToJSON(value.permissions),
    };
}

