/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticlePermissionsType } from './ArticlePermissionsType';
import {
    ArticlePermissionsTypeFromJSON,
    ArticlePermissionsTypeFromJSONTyped,
    ArticlePermissionsTypeToJSON,
    instanceOfArticlePermissionsType
} from './ArticlePermissionsType';

/**
 * JSON representation of article permissions request
 */
export type ArticlePermissionsRequestModelJson = {
    editableBy?: string;
    editorUserIds?: number[];
    editorUserGroupIds?: number[];
}

/**
 * 
 * @export
 * @interface ArticlePermissionsRequestModel
 */
export interface ArticlePermissionsRequestModel {
    /**
     * 
     * @type {ArticlePermissionsType}
     * @memberof ArticlePermissionsRequestModel
     */
    editableBy?: ArticlePermissionsType;
    /**
     * Editor User IDs. The identity of users who can edit this article
     * @type {Array<number>}
     * @memberof ArticlePermissionsRequestModel
     */
    editorUserIds?: Array<number>;
    /**
     * Editor User Group IDs. The identity of user groups who can edit this article
     * @type {Array<number>}
     * @memberof ArticlePermissionsRequestModel
     */
    editorUserGroupIds?: Array<number>;
}

/**
 * Check if a given object implements the ArticlePermissionsRequestModel interface.
 */
export function instanceOfArticlePermissionsRequestModel(value: unknown): value is ArticlePermissionsRequestModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<ArticlePermissionsRequestModel>;
    
    // All fields are optional, so we just need to check types if they exist
    if (v.editableBy !== undefined && !instanceOfArticlePermissionsType(v.editableBy)) return false;
    if (v.editorUserIds !== undefined && !Array.isArray(v.editorUserIds)) return false;
    if (v.editorUserGroupIds !== undefined && !Array.isArray(v.editorUserGroupIds)) return false;
    
    return true;
}

export function ArticlePermissionsRequestModelFromJSON(json: ArticlePermissionsRequestModelJson): ArticlePermissionsRequestModel {
    return ArticlePermissionsRequestModelFromJSONTyped(json, false);
}

export function ArticlePermissionsRequestModelFromJSONTyped(
    json: ArticlePermissionsRequestModelJson,
    ignoreDiscriminator: boolean
): ArticlePermissionsRequestModel {
    if (!json) {
        throw new Error('ArticlePermissionsRequestModel JSON cannot be null or undefined');
    }
    
    return {
        'editableBy': json.editableBy === undefined ? undefined : ArticlePermissionsTypeFromJSON(json.editableBy),
        'editorUserIds': json.editorUserIds,
        'editorUserGroupIds': json.editorUserGroupIds,
    };
}

export function ArticlePermissionsRequestModelToJSON(value?: ArticlePermissionsRequestModel | null): ArticlePermissionsRequestModelJson | null {
    if (!value) {
        return null;
    }
    
    return {
        'editableBy': value.editableBy === undefined ? undefined : ArticlePermissionsTypeToJSON(value.editableBy) ?? undefined,
        'editorUserIds': value.editorUserIds,
        'editorUserGroupIds': value.editorUserGroupIds,
    };
}

