/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Article Type
 * @export
 */
export const ArticleType = {
    KnowledgeArticle: 'knowledgeArticle',
    Announcement: 'announcement',
    Policy: 'policy',
    HowToGuide: 'howToGuide'
} as const;
export type ArticleType = typeof ArticleType[keyof typeof ArticleType];


export function instanceOfArticleType(value: any): boolean {
    for (const key in ArticleType) {
        if (Object.prototype.hasOwnProperty.call(ArticleType, key)) {
            if (ArticleType[key as keyof typeof ArticleType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ArticleTypeFromJSON(json: any): ArticleType {
    return ArticleTypeFromJSONTyped(json, false);
}

export function ArticleTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleType {
    return json as ArticleType;
}

export function ArticleTypeToJSON(value?: ArticleType | null): any {
    return value as any;
}

