/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticlePermissionsType } from './ArticlePermissionsType';
import {
    ArticlePermissionsTypeFromJSON,
    ArticlePermissionsTypeFromJSONTyped,
    ArticlePermissionsTypeToJSON,
} from './ArticlePermissionsType';

/**
 * 
 * @export
 * @interface ArticlePermissionsRequestModel
 */
export interface ArticlePermissionsRequestModel {
    /**
     * 
     * @type {ArticlePermissionsType}
     * @memberof ArticlePermissionsRequestModel
     */
    editableBy?: ArticlePermissionsType;
    /**
     * Editor User IDs. The identity of users who can edit this article
     * @type {Array<number>}
     * @memberof ArticlePermissionsRequestModel
     */
    editorUserIds?: Array<number>;
    /**
     * Editor User Group IDs. The identity of user groups who can edit this article
     * @type {Array<number>}
     * @memberof ArticlePermissionsRequestModel
     */
    editorUserGroupIds?: Array<number>;
}



/**
 * Check if a given object implements the ArticlePermissionsRequestModel interface.
 */
export function instanceOfArticlePermissionsRequestModel(value: object): value is ArticlePermissionsRequestModel {
    return true;
}

export function ArticlePermissionsRequestModelFromJSON(json: any): ArticlePermissionsRequestModel {
    return ArticlePermissionsRequestModelFromJSONTyped(json, false);
}

export function ArticlePermissionsRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlePermissionsRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'editableBy': json['editableBy'] == null ? undefined : ArticlePermissionsTypeFromJSON(json['editableBy']),
        'editorUserIds': json['editorUserIds'] == null ? undefined : json['editorUserIds'],
        'editorUserGroupIds': json['editorUserGroupIds'] == null ? undefined : json['editorUserGroupIds'],
    };
}

export function ArticlePermissionsRequestModelToJSON(value?: ArticlePermissionsRequestModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'editableBy': ArticlePermissionsTypeToJSON(value['editableBy']),
        'editorUserIds': value['editorUserIds'],
        'editorUserGroupIds': value['editorUserGroupIds'],
    };
}

