/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
    instanceOfUserSummaryResponseModel
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface ArticleSearchResultModel
 */
export interface ArticleSearchResultModel {
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleSearchResultModel
     */
    articleId?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleSearchResultModel
     */
    viewCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    snippet?: string;
    /**
     * 
     * @type {Array<TagSummaryResponseModel>}
     * @memberof ArticleSearchResultModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleSearchResultModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {Date}
     * @memberof ArticleSearchResultModel
     */
    creationDate?: Date;
}

/**
 * JSON representation of article search result
 */
export type ArticleSearchResultModelJson = {
    type?: string;
    articleId?: number;
    viewCount?: number;
    title?: string;
    snippet?: string;
    tags?: unknown[];
    owner?: unknown;
    creationDate?: string;
}

/**
 * Check if a given object implements the ArticleSearchResultModel interface.
 */
export function instanceOfArticleSearchResultModel(value: unknown): value is ArticleSearchResultModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<ArticleSearchResultModel>;
    
    return (
        (v.type === undefined || typeof v.type === 'string') &&
        (v.articleId === undefined || typeof v.articleId === 'number') &&
        (v.viewCount === undefined || typeof v.viewCount === 'number') &&
        (v.title === undefined || typeof v.title === 'string') &&
        (v.snippet === undefined || typeof v.snippet === 'string') &&
        (v.tags === undefined || Array.isArray(v.tags)) &&
        (v.owner === undefined || instanceOfUserSummaryResponseModel(v.owner)) &&
        (v.creationDate === undefined || v.creationDate instanceof Date)
    );
}

export function ArticleSearchResultModelFromJSON(json: ArticleSearchResultModelJson): ArticleSearchResultModel {
    return ArticleSearchResultModelFromJSONTyped(json, false);
}

export function ArticleSearchResultModelFromJSONTyped(
    json: ArticleSearchResultModelJson,
    ignoreDiscriminator: boolean
): ArticleSearchResultModel {
    if (!json) {
        throw new Error('ArticleSearchResultModel JSON cannot be null or undefined');
    }
    
    return {
        'type': json.type,
        'articleId': json.articleId,
        'viewCount': json.viewCount,
        'title': json.title,
        'snippet': json.snippet,
        'tags': json.tags === undefined ? undefined : json.tags.map(TagSummaryResponseModelFromJSON),
        'owner': json.owner === undefined ? undefined : UserSummaryResponseModelFromJSON(json.owner),
        'creationDate': json.creationDate === undefined ? undefined : new Date(json.creationDate)
    };
}

export function ArticleSearchResultModelToJSON(value?: ArticleSearchResultModel | null): ArticleSearchResultModelJson | null {
    if (!value) {
        return null;
    }
    
    return {
        'type': value.type,
        'articleId': value.articleId,
        'viewCount': value.viewCount,
        'title': value.title,
        'snippet': value.snippet,
        'tags': value.tags === undefined ? undefined : value.tags.map(TagSummaryResponseModelToJSON),
        'owner': value.owner === undefined ? undefined : UserSummaryResponseModelToJSON(value.owner),
        'creationDate': value.creationDate === undefined ? undefined : value.creationDate.toISOString()
    };
}

