/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Article Permissions Type
 * @export
 */
export const ArticlePermissionsType = {
    OwnerOnly: 'ownerOnly',
    SpecificEditors: 'specificEditors',
    Everyone: 'everyone'
} as const;
export type ArticlePermissionsType = typeof ArticlePermissionsType[keyof typeof ArticlePermissionsType];

export function instanceOfArticlePermissionsType(value: unknown): value is ArticlePermissionsType {
    return typeof value === 'string' && Object.values(ArticlePermissionsType).includes(value as ArticlePermissionsType);
}

export function ArticlePermissionsTypeFromJSON(json: unknown): ArticlePermissionsType {
    return ArticlePermissionsTypeFromJSONTyped(json, false);
}

export function ArticlePermissionsTypeFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ArticlePermissionsType {
    if (!instanceOfArticlePermissionsType(json)) {
        throw new Error('Invalid ArticlePermissionsType value');
    }
    return json;
}

export function ArticlePermissionsTypeToJSON(value?: ArticlePermissionsType | null): ArticlePermissionsType | null {
    return value ?? null;
}

