/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
    instanceOfUserSummaryResponseModel
} from './UserSummaryResponseModel';
import type { ArticleType } from './ArticleType';
import {
    ArticleTypeFromJSON,
    ArticleTypeFromJSONTyped,
    ArticleTypeToJSON,
    instanceOfArticleType
} from './ArticleType';

/**
 * 
 * @export
 * @interface ArticleSummaryResponseModel
 */
export interface ArticleSummaryResponseModel {
    /**
     * ID. The article's unique identifier.
     * @type {number}
     * @memberof ArticleSummaryResponseModel
     */
    id?: number;
    /**
     * 
     * @type {ArticleType}
     * @memberof ArticleSummaryResponseModel
     */
    type?: ArticleType;
    /**
     * Title. The actual article, stated briefly in one sentence.
     * @type {string}
     * @memberof ArticleSummaryResponseModel
     */
    title?: string;
    /**
     * Body. Additional details to clarify the article.
     * @type {string}
     * @memberof ArticleSummaryResponseModel
     */
    body?: string;
    /**
     * Tags. Tags associated with the article.
     * @type {Array<TagSummaryResponseModel>}
     * @memberof ArticleSummaryResponseModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleSummaryResponseModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleSummaryResponseModel
     */
    lastEditor?: UserSummaryResponseModel;
    /**
     * Creation date. The date and time the article was created.
     * @type {Date}
     * @memberof ArticleSummaryResponseModel
     */
    creationDate?: Date;
    /**
     * Last activity date. The date and time the article or one of its answers last had significant activity. This includes (but is not limited to) an edit, rollback, change to tags, new answer, bounty added, bump.
     * @type {Date}
     * @memberof ArticleSummaryResponseModel
     */
    lastActivityDate?: Date | null;
    /**
     * Score. Calculated by subtracting the number of downvotes from the number of upvotes
     * @type {number}
     * @memberof ArticleSummaryResponseModel
     */
    score?: number;
    /**
     * View count. The number of times users have viewed this article.
     * @type {number}
     * @memberof ArticleSummaryResponseModel
     */
    viewCount?: number;
    /**
     * Share URL. The article's direct URL.
     * @type {string}
     * @memberof ArticleSummaryResponseModel
     */
    shareUrl?: string;
    /**
     * Is deleted. Returns true if the article was deleted.
     * @type {boolean}
     * @memberof ArticleSummaryResponseModel
     */
    isDeleted?: boolean;
    /**
     * Is obsolete. Returns true if the article was marked by a moderator as obsolete.
     * @type {boolean}
     * @memberof ArticleSummaryResponseModel
     */
    isObsolete?: boolean;
    /**
     * Is closed. Returns true if the article was closed by a moderator.
     * @type {boolean}
     * @memberof ArticleSummaryResponseModel
     */
    isClosed?: boolean;
}

/**
 * JSON representation of article summary response
 */
export type ArticleSummaryResponseModelJson = {
    id?: number;
    type?: ArticleType;
    title?: string;
    body?: string;
    tags?: unknown[];
    owner?: unknown;
    lastEditor?: unknown;
    creationDate?: string;
    lastActivityDate?: string | null;
    score?: number;
    viewCount?: number;
    shareUrl?: string;
    isDeleted?: boolean;
    isObsolete?: boolean;
    isClosed?: boolean;
}

/**
 * Check if a given object implements the ArticleSummaryResponseModel interface.
 */
export function instanceOfArticleSummaryResponseModel(value: unknown): value is ArticleSummaryResponseModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<ArticleSummaryResponseModel>;
    
    return (
        (v.id === undefined || typeof v.id === 'number') &&
        (v.type === undefined || instanceOfArticleType(v.type)) &&
        (v.title === undefined || typeof v.title === 'string') &&
        (v.body === undefined || typeof v.body === 'string') &&
        (v.tags === undefined || Array.isArray(v.tags)) &&
        (v.owner === undefined || instanceOfUserSummaryResponseModel(v.owner)) &&
        (v.lastEditor === undefined || instanceOfUserSummaryResponseModel(v.lastEditor)) &&
        (v.creationDate === undefined || v.creationDate instanceof Date) &&
        (v.lastActivityDate === undefined || v.lastActivityDate === null || v.lastActivityDate instanceof Date) &&
        (v.score === undefined || typeof v.score === 'number') &&
        (v.viewCount === undefined || typeof v.viewCount === 'number') &&
        (v.shareUrl === undefined || typeof v.shareUrl === 'string') &&
        (v.isDeleted === undefined || typeof v.isDeleted === 'boolean') &&
        (v.isObsolete === undefined || typeof v.isObsolete === 'boolean') &&
        (v.isClosed === undefined || typeof v.isClosed === 'boolean')
    );
}

export function ArticleSummaryResponseModelFromJSON(json: ArticleSummaryResponseModelJson): ArticleSummaryResponseModel {
    return ArticleSummaryResponseModelFromJSONTyped(json, false);
}

export function ArticleSummaryResponseModelFromJSONTyped(
    json: ArticleSummaryResponseModelJson,
    ignoreDiscriminator: boolean
): ArticleSummaryResponseModel {
    if (!json) {
        throw new Error('ArticleSummaryResponseModel JSON cannot be null or undefined');
    }
    
    return {
        'id': json.id,
        'type': json.type === undefined ? undefined : ArticleTypeFromJSON(json.type),
        'title': json.title,
        'body': json.body,
        'tags': json.tags === undefined ? undefined : json.tags.map(TagSummaryResponseModelFromJSON),
        'owner': json.owner === undefined ? undefined : UserSummaryResponseModelFromJSON(json.owner),
        'lastEditor': json.lastEditor === undefined ? undefined : UserSummaryResponseModelFromJSON(json.lastEditor),
        'creationDate': json.creationDate === undefined ? undefined : new Date(json.creationDate),
        'lastActivityDate': json.lastActivityDate === undefined ? undefined : json.lastActivityDate === null ? null : new Date(json.lastActivityDate),
        'score': json.score,
        'viewCount': json.viewCount,
        'shareUrl': json.shareUrl,
        'isDeleted': json.isDeleted,
        'isObsolete': json.isObsolete,
        'isClosed': json.isClosed
    };
}

export function ArticleSummaryResponseModelToJSON(value?: ArticleSummaryResponseModel | null): ArticleSummaryResponseModelJson | null {
    if (!value) {
        return null;
    }
    
    const type = value.type === undefined ? undefined : ArticleTypeToJSON(value.type);
    if (type === null) {
        throw new Error('Invalid ArticleType value');
    }
    
    return {
        'id': value.id,
        'type': type,
        'title': value.title,
        'body': value.body,
        'tags': value.tags === undefined ? undefined : value.tags.map(TagSummaryResponseModelToJSON),
        'owner': value.owner === undefined ? undefined : UserSummaryResponseModelToJSON(value.owner),
        'lastEditor': value.lastEditor === undefined ? undefined : UserSummaryResponseModelToJSON(value.lastEditor),
        'creationDate': value.creationDate === undefined ? undefined : value.creationDate.toISOString(),
        'lastActivityDate': value.lastActivityDate === undefined ? undefined : value.lastActivityDate === null ? null : value.lastActivityDate.toISOString(),
        'score': value.score,
        'viewCount': value.viewCount,
        'shareUrl': value.shareUrl,
        'isDeleted': value.isDeleted,
        'isObsolete': value.isObsolete,
        'isClosed': value.isClosed
    };
}

