/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Article Type
 * @export
 */
export const ArticleType = {
    KnowledgeArticle: 'knowledgeArticle',
    Announcement: 'announcement',
    Policy: 'policy',
    HowToGuide: 'howToGuide'
} as const;
export type ArticleType = typeof ArticleType[keyof typeof ArticleType];

export function instanceOfArticleType(value: unknown): value is ArticleType {
    return typeof value === 'string' && Object.values(ArticleType).includes(value as ArticleType);
}

export function ArticleTypeFromJSON(json: unknown): ArticleType {
    return ArticleTypeFromJSONTyped(json, false);
}

export function ArticleTypeFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ArticleType {
    if (!instanceOfArticleType(json)) {
        throw new Error('Invalid ArticleType value');
    }
    return json;
}

export function ArticleTypeToJSON(value?: ArticleType | null): ArticleType | null {
    return value ?? null;
}

