/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ArticlePermissionsResponseModel } from './ArticlePermissionsResponseModel';
import {
    ArticlePermissionsResponseModelFromJSON,
    ArticlePermissionsResponseModelFromJSONTyped,
    ArticlePermissionsResponseModelToJSON,
    instanceOfArticlePermissionsResponseModel
} from './ArticlePermissionsResponseModel';
import type { CommunitySummaryResponseModel } from './CommunitySummaryResponseModel';
import {
    CommunitySummaryResponseModelFromJSON,
    CommunitySummaryResponseModelFromJSONTyped,
    CommunitySummaryResponseModelToJSON,
    instanceOfCommunitySummaryResponseModel
} from './CommunitySummaryResponseModel';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
    instanceOfTagSummaryResponseModel
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
    instanceOfUserSummaryResponseModel
} from './UserSummaryResponseModel';
import type { ArticleType } from './ArticleType';
import {
    ArticleTypeFromJSON,
    ArticleTypeFromJSONTyped,
    ArticleTypeToJSON,
    instanceOfArticleType
} from './ArticleType';

/**
 * JSON representation of an article response
 */
export type ArticleResponseModelJson = {
    communities?: unknown[];
    id?: number;
    type?: string;
    title?: string;
    body?: string;
    tags?: unknown[];
    owner?: unknown;
    lastEditor?: unknown;
    creationDate?: string;
    lastActivityDate?: string | null;
    score?: number;
    viewCount?: number;
    shareUrl?: string;
    isDeleted?: boolean;
    isObsolete?: boolean;
    isClosed?: boolean;
    bodyMarkdown?: string;
    userIsFollowing?: boolean;
    userHasUpvoted?: boolean;
    userHasDownvoted?: boolean;
    userCanEdit?: boolean;
    permissions?: unknown;
}

/**
 * 
 * @export
 * @interface ArticleResponseModel
 */
export interface ArticleResponseModel {
    /**
     * 
     * @type {Array<CommunitySummaryResponseModel>}
     * @memberof ArticleResponseModel
     */
    communities?: Array<CommunitySummaryResponseModel>;
    /**
     * ID. The article's unique identifier.
     * @type {number}
     * @memberof ArticleResponseModel
     */
    id?: number;
    /**
     * 
     * @type {ArticleType}
     * @memberof ArticleResponseModel
     */
    type?: ArticleType;
    /**
     * Title. The actual article, stated briefly in one sentence.
     * @type {string}
     * @memberof ArticleResponseModel
     */
    title?: string;
    /**
     * Body. Additional details to clarify the article.
     * @type {string}
     * @memberof ArticleResponseModel
     */
    body?: string;
    /**
     * Tags. Tags associated with the article.
     * @type {Array<TagSummaryResponseModel>}
     * @memberof ArticleResponseModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleResponseModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleResponseModel
     */
    lastEditor?: UserSummaryResponseModel;
    /**
     * Creation date. The date and time the article was created.
     * @type {Date}
     * @memberof ArticleResponseModel
     */
    creationDate?: Date;
    /**
     * Last activity date. The date and time the article or one of its answers last had significant activity. This includes (but is not limited to) an edit, rollback, change to tags, new answer, bounty added, bump.
     * @type {Date}
     * @memberof ArticleResponseModel
     */
    lastActivityDate?: Date | null;
    /**
     * Score. Calculated by subtracting the number of downvotes from the number of upvotes
     * @type {number}
     * @memberof ArticleResponseModel
     */
    score?: number;
    /**
     * View count. The number of times users have viewed this article.
     * @type {number}
     * @memberof ArticleResponseModel
     */
    viewCount?: number;
    /**
     * Share URL. The article's direct URL.
     * @type {string}
     * @memberof ArticleResponseModel
     */
    shareUrl?: string;
    /**
     * Is deleted. Returns true if the article was deleted.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    isDeleted?: boolean;
    /**
     * Is obsolete. Returns true if the article was marked by a moderator as obsolete.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    isObsolete?: boolean;
    /**
     * Is closed. Returns true if the article was closed by a moderator.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    isClosed?: boolean;
    /**
     * Body in Markdown format.
     * @type {string}
     * @memberof ArticleResponseModel
     */
    bodyMarkdown?: string;
    /**
     * User is following. Returns true if the logged-in user followed the article.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    userIsFollowing?: boolean;
    /**
     * User has upvoted. Returns true if the logged-in user has upvoted the article.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    userHasUpvoted?: boolean;
    /**
     * User has downvoted. Returns true if the logged-in user has downvoted the article.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    userHasDownvoted?: boolean;
    /**
     * User can edit. Returns true if the this article can be edited by the authenticated user.
     * @type {boolean}
     * @memberof ArticleResponseModel
     */
    userCanEdit?: boolean;
    /**
     * 
     * @type {ArticlePermissionsResponseModel}
     * @memberof ArticleResponseModel
     */
    permissions?: ArticlePermissionsResponseModel;
}

/**
 * Check if a given object implements the ArticleResponseModel interface.
 */
export function instanceOfArticleResponseModel(value: unknown): value is ArticleResponseModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<ArticleResponseModel>;
    
    // All fields are optional, so we just need to check types if they exist
    if (v.id !== undefined && typeof v.id !== 'number') return false;
    if (v.type !== undefined && !instanceOfArticleType(v.type)) return false;
    if (v.title !== undefined && typeof v.title !== 'string') return false;
    if (v.body !== undefined && typeof v.body !== 'string') return false;
    if (v.tags !== undefined && !Array.isArray(v.tags)) return false;
    if (v.owner !== undefined && !instanceOfUserSummaryResponseModel(v.owner)) return false;
    if (v.lastEditor !== undefined && !instanceOfUserSummaryResponseModel(v.lastEditor)) return false;
    if (v.creationDate !== undefined && !(v.creationDate instanceof Date)) return false;
    if (v.lastActivityDate !== undefined && v.lastActivityDate !== null && !(v.lastActivityDate instanceof Date)) return false;
    if (v.score !== undefined && typeof v.score !== 'number') return false;
    if (v.viewCount !== undefined && typeof v.viewCount !== 'number') return false;
    if (v.shareUrl !== undefined && typeof v.shareUrl !== 'string') return false;
    if (v.isDeleted !== undefined && typeof v.isDeleted !== 'boolean') return false;
    if (v.isObsolete !== undefined && typeof v.isObsolete !== 'boolean') return false;
    if (v.isClosed !== undefined && typeof v.isClosed !== 'boolean') return false;
    if (v.bodyMarkdown !== undefined && typeof v.bodyMarkdown !== 'string') return false;
    if (v.userIsFollowing !== undefined && typeof v.userIsFollowing !== 'boolean') return false;
    if (v.userHasUpvoted !== undefined && typeof v.userHasUpvoted !== 'boolean') return false;
    if (v.userHasDownvoted !== undefined && typeof v.userHasDownvoted !== 'boolean') return false;
    if (v.userCanEdit !== undefined && typeof v.userCanEdit !== 'boolean') return false;
    if (v.permissions !== undefined && !instanceOfArticlePermissionsResponseModel(v.permissions)) return false;
    
    return true;
}

export function ArticleResponseModelFromJSON(json: ArticleResponseModelJson): ArticleResponseModel {
    return ArticleResponseModelFromJSONTyped(json, false);
}

export function ArticleResponseModelFromJSONTyped(
    json: ArticleResponseModelJson,
    ignoreDiscriminator: boolean
): ArticleResponseModel {
    if (!json) {
        throw new Error('ArticleResponseModel JSON cannot be null or undefined');
    }
    
    return {
        'communities': json.communities === undefined ? undefined : json.communities.map(CommunitySummaryResponseModelFromJSON),
        'id': json.id,
        'type': json.type === undefined ? undefined : ArticleTypeFromJSON(json.type),
        'title': json.title,
        'body': json.body,
        'tags': json.tags === undefined ? undefined : json.tags.map(TagSummaryResponseModelFromJSON),
        'owner': json.owner === undefined ? undefined : UserSummaryResponseModelFromJSON(json.owner),
        'lastEditor': json.lastEditor === undefined ? undefined : UserSummaryResponseModelFromJSON(json.lastEditor),
        'creationDate': json.creationDate === undefined ? undefined : new Date(json.creationDate),
        'lastActivityDate': json.lastActivityDate === undefined ? undefined : json.lastActivityDate === null ? null : new Date(json.lastActivityDate),
        'score': json.score,
        'viewCount': json.viewCount,
        'shareUrl': json.shareUrl,
        'isDeleted': json.isDeleted,
        'isObsolete': json.isObsolete,
        'isClosed': json.isClosed,
        'bodyMarkdown': json.bodyMarkdown,
        'userIsFollowing': json.userIsFollowing,
        'userHasUpvoted': json.userHasUpvoted,
        'userHasDownvoted': json.userHasDownvoted,
        'userCanEdit': json.userCanEdit,
        'permissions': json.permissions === undefined ? undefined : ArticlePermissionsResponseModelFromJSON(json.permissions),
    };
}

export function ArticleResponseModelToJSON(value?: ArticleResponseModel | null): ArticleResponseModelJson | null {
    if (!value) {
        return null;
    }
    
    const type = value.type === undefined ? undefined : ArticleTypeToJSON(value.type);
    if (type === null) {
        throw new Error('Invalid ArticleType value');
    }
    
    return {
        'communities': value.communities === undefined ? undefined : value.communities.map(CommunitySummaryResponseModelToJSON),
        'id': value.id,
        'type': type,
        'title': value.title,
        'body': value.body,
        'tags': value.tags === undefined ? undefined : value.tags.map(TagSummaryResponseModelToJSON),
        'owner': value.owner === undefined ? undefined : UserSummaryResponseModelToJSON(value.owner),
        'lastEditor': value.lastEditor === undefined ? undefined : UserSummaryResponseModelToJSON(value.lastEditor),
        'creationDate': value.creationDate === undefined ? undefined : value.creationDate.toISOString(),
        'lastActivityDate': value.lastActivityDate === undefined ? undefined : value.lastActivityDate === null ? null : value.lastActivityDate.toISOString(),
        'score': value.score,
        'viewCount': value.viewCount,
        'shareUrl': value.shareUrl,
        'isDeleted': value.isDeleted,
        'isObsolete': value.isObsolete,
        'isClosed': value.isClosed,
        'bodyMarkdown': value.bodyMarkdown,
        'userIsFollowing': value.userIsFollowing,
        'userHasUpvoted': value.userHasUpvoted,
        'userHasDownvoted': value.userHasDownvoted,
        'userCanEdit': value.userCanEdit,
        'permissions': value.permissions === undefined ? undefined : ArticlePermissionsResponseModelToJSON(value.permissions),
    };
}

