/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const ArticlePermissionsType = {
    OwnerOnly: 'ownerOnly',
    SpecificEditors: 'specificEditors',
    Everyone: 'everyone'
} as const;
export type ArticlePermissionsType = typeof ArticlePermissionsType[keyof typeof ArticlePermissionsType];


export function instanceOfArticlePermissionsType(value: any): boolean {
    for (const key in ArticlePermissionsType) {
        if (Object.prototype.hasOwnProperty.call(ArticlePermissionsType, key)) {
            if (ArticlePermissionsType[key as keyof typeof ArticlePermissionsType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ArticlePermissionsTypeFromJSON(json: any): ArticlePermissionsType {
    return ArticlePermissionsTypeFromJSONTyped(json, false);
}

export function ArticlePermissionsTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticlePermissionsType {
    return json as ArticlePermissionsType;
}

export function ArticlePermissionsTypeToJSON(value?: ArticlePermissionsType | null): any {
    return value as any;
}

