/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Articles sort parameter
 * @export
 */
export const ArticleSortParameter = {
    Activity: 'activity',
    Creation: 'creation',
    Score: 'score'
} as const;
export type ArticleSortParameter = typeof ArticleSortParameter[keyof typeof ArticleSortParameter];


export function instanceOfArticleSortParameter(value: any): boolean {
    for (const key in ArticleSortParameter) {
        if (Object.prototype.hasOwnProperty.call(ArticleSortParameter, key)) {
            if (ArticleSortParameter[key as keyof typeof ArticleSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ArticleSortParameterFromJSON(json: any): ArticleSortParameter {
    return ArticleSortParameterFromJSONTyped(json, false);
}

export function ArticleSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleSortParameter {
    return json as ArticleSortParameter;
}

export function ArticleSortParameterToJSON(value?: ArticleSortParameter | null): any {
    return value as any;
}

