/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface ArticleSearchResultModel
 */
export interface ArticleSearchResultModel {
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    readonly type?: string;
    /**
     * 
     * @type {number}
     * @memberof ArticleSearchResultModel
     */
    articleId?: number;
    /**
     * 
     * @type {number}
     * @memberof ArticleSearchResultModel
     */
    viewCount?: number;
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof ArticleSearchResultModel
     */
    snippet?: string;
    /**
     * 
     * @type {Array<TagSummaryResponseModel>}
     * @memberof ArticleSearchResultModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof ArticleSearchResultModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {Date}
     * @memberof ArticleSearchResultModel
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the ArticleSearchResultModel interface.
 */
export function instanceOfArticleSearchResultModel(value: object): value is ArticleSearchResultModel {
    return true;
}

export function ArticleSearchResultModelFromJSON(json: any): ArticleSearchResultModel {
    return ArticleSearchResultModelFromJSONTyped(json, false);
}

export function ArticleSearchResultModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ArticleSearchResultModel {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'articleId': json['articleId'] == null ? undefined : json['articleId'],
        'viewCount': json['viewCount'] == null ? undefined : json['viewCount'],
        'title': json['title'] == null ? undefined : json['title'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagSummaryResponseModelFromJSON)),
        'owner': json['owner'] == null ? undefined : UserSummaryResponseModelFromJSON(json['owner']),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

export function ArticleSearchResultModelToJSON(value?: ArticleSearchResultModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'articleId': value['articleId'],
        'viewCount': value['viewCount'],
        'title': value['title'],
        'snippet': value['snippet'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagSummaryResponseModelToJSON)),
        'owner': UserSummaryResponseModelToJSON(value['owner']),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

