/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Articles sort parameter
 * @export
 */
export const ArticleSortParameter = {
    Activity: 'activity',
    Creation: 'creation',
    Score: 'score'
} as const;
export type ArticleSortParameter = typeof ArticleSortParameter[keyof typeof ArticleSortParameter];


export function instanceOfArticleSortParameter(value: unknown): value is ArticleSortParameter {
    return typeof value === 'string' && Object.values(ArticleSortParameter).includes(value as ArticleSortParameter);
}

export function ArticleSortParameterFromJSON(json: unknown): ArticleSortParameter {
    return ArticleSortParameterFromJSONTyped(json, false);
}

export function ArticleSortParameterFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): ArticleSortParameter {
    if (!instanceOfArticleSortParameter(json)) {
        throw new Error('Invalid ArticleSortParameter value');
    }
    return json;
}

export function ArticleSortParameterToJSON(value?: ArticleSortParameter | null): ArticleSortParameter | null {
    return value ?? null;
}

