/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BountyResponseModel
 */
export interface BountyResponseModel {
    /**
     * Amount. The number of points the question asker will reward the poster of an accepted answer.
     * @type {number}
     * @memberof BountyResponseModel
     */
    amount?: number;
    /**
     * Closes. The date and time the bounty expires.
     * @type {Date}
     * @memberof BountyResponseModel
     */
    closes?: Date;
}

/**
 * Check if a given object implements the BountyResponseModel interface.
 */
export function instanceOfBountyResponseModel(value: object): value is BountyResponseModel {
    return true;
}

export function BountyResponseModelFromJSON(json: any): BountyResponseModel {
    return BountyResponseModelFromJSONTyped(json, false);
}

export function BountyResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): BountyResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'amount': json['amount'] == null ? undefined : json['amount'],
        'closes': json['closes'] == null ? undefined : (new Date(json['closes'])),
    };
}

export function BountyResponseModelToJSON(value?: BountyResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'amount': value['amount'],
        'closes': value['closes'] == null ? undefined : ((value['closes']).toISOString()),
    };
}

