/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CollectionsSortParameter = {
    Creation: 'creation',
    LastEdit: 'lastEdit'
} as const;
export type CollectionsSortParameter = typeof CollectionsSortParameter[keyof typeof CollectionsSortParameter];


export function instanceOfCollectionsSortParameter(value: any): boolean {
    for (const key in CollectionsSortParameter) {
        if (Object.prototype.hasOwnProperty.call(CollectionsSortParameter, key)) {
            if (CollectionsSortParameter[key as keyof typeof CollectionsSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CollectionsSortParameterFromJSON(json: any): CollectionsSortParameter {
    return CollectionsSortParameterFromJSONTyped(json, false);
}

export function CollectionsSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionsSortParameter {
    return json as CollectionsSortParameter;
}

export function CollectionsSortParameterToJSON(value?: CollectionsSortParameter | null): any {
    return value as any;
}

