/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionRequestModel
 */
export interface CollectionRequestModel {
    /**
     * Title. A brief title to distinguish the collection and its contents.
     * @type {string}
     * @memberof CollectionRequestModel
     */
    title?: string;
    /**
     * Description. A detailed description of what the collection contains. Supports Markdown.
     * @type {string}
     * @memberof CollectionRequestModel
     */
    description?: string;
    /**
     * Editor user IDs. The IDs of users who can modify this collection.
     * @type {Array<number>}
     * @memberof CollectionRequestModel
     */
    editorUserIds?: Array<number>;
    /**
     * Editor user group IDs. The IDs of user groups whose members can modify this collection.
     * @type {Array<number>}
     * @memberof CollectionRequestModel
     */
    editorUserGroupIds?: Array<number>;
    /**
     * Content IDs. The IDs of questions and/or articles that this collection contains, in order.
     * @type {Array<number>}
     * @memberof CollectionRequestModel
     */
    contentIds?: Array<number>;
}

/**
 * Check if a given object implements the CollectionRequestModel interface.
 */
export function instanceOfCollectionRequestModel(value: object): value is CollectionRequestModel {
    return true;
}

export function CollectionRequestModelFromJSON(json: any): CollectionRequestModel {
    return CollectionRequestModelFromJSONTyped(json, false);
}

export function CollectionRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'editorUserIds': json['editorUserIds'] == null ? undefined : json['editorUserIds'],
        'editorUserGroupIds': json['editorUserGroupIds'] == null ? undefined : json['editorUserGroupIds'],
        'contentIds': json['contentIds'] == null ? undefined : json['contentIds'],
    };
}

export function CollectionRequestModelToJSON(value?: CollectionRequestModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'description': value['description'],
        'editorUserIds': value['editorUserIds'],
        'editorUserGroupIds': value['editorUserGroupIds'],
        'contentIds': value['contentIds'],
    };
}

