/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const CollectionsPermissionsFilter = {
    All: 'all',
    Owned: 'owned',
    Editable: 'editable'
} as const;
export type CollectionsPermissionsFilter = typeof CollectionsPermissionsFilter[keyof typeof CollectionsPermissionsFilter];


export function instanceOfCollectionsPermissionsFilter(value: any): boolean {
    for (const key in CollectionsPermissionsFilter) {
        if (Object.prototype.hasOwnProperty.call(CollectionsPermissionsFilter, key)) {
            if (CollectionsPermissionsFilter[key as keyof typeof CollectionsPermissionsFilter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CollectionsPermissionsFilterFromJSON(json: any): CollectionsPermissionsFilter {
    return CollectionsPermissionsFilterFromJSONTyped(json, false);
}

export function CollectionsPermissionsFilterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionsPermissionsFilter {
    return json as CollectionsPermissionsFilter;
}

export function CollectionsPermissionsFilterToJSON(value?: CollectionsPermissionsFilter | null): any {
    return value as any;
}

