/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionContentType } from './CollectionContentType';
import {
    CollectionContentTypeFromJSON,
    CollectionContentTypeFromJSONTyped,
    CollectionContentTypeToJSON,
} from './CollectionContentType';

/**
 * A content item (post) returned by the collection endpoint. This model makes no distinction between questions and articles and returns them together, filtered and sorted.
 * @export
 * @interface CollectionContentSummaryResponseModel
 */
export interface CollectionContentSummaryResponseModel {
    /**
     * ID. The content's unique identifier.
     * @type {number}
     * @memberof CollectionContentSummaryResponseModel
     */
    id?: number;
    /**
     * 
     * @type {CollectionContentType}
     * @memberof CollectionContentSummaryResponseModel
     */
    type?: CollectionContentType;
    /**
     * Title. The title of the question or article.
     * @type {string}
     * @memberof CollectionContentSummaryResponseModel
     */
    title?: string;
}



/**
 * Check if a given object implements the CollectionContentSummaryResponseModel interface.
 */
export function instanceOfCollectionContentSummaryResponseModel(value: object): value is CollectionContentSummaryResponseModel {
    return true;
}

export function CollectionContentSummaryResponseModelFromJSON(json: any): CollectionContentSummaryResponseModel {
    return CollectionContentSummaryResponseModelFromJSONTyped(json, false);
}

export function CollectionContentSummaryResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionContentSummaryResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'type': json['type'] == null ? undefined : CollectionContentTypeFromJSON(json['type']),
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function CollectionContentSummaryResponseModelToJSON(value?: CollectionContentSummaryResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'type': CollectionContentTypeToJSON(value['type']),
        'title': value['title'],
    };
}

