/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityLeaveModel
 */
export interface CommunityLeaveModel {
    /**
     * Member User IDs. The identity of users who will leave this community
     * @type {Array<number>}
     * @memberof CommunityLeaveModel
     */
    memberUserIds?: Array<number>;
}

/**
 * Check if a given object implements the CommunityLeaveModel interface.
 */
export function instanceOfCommunityLeaveModel(value: object): value is CommunityLeaveModel {
    return true;
}

export function CommunityLeaveModelFromJSON(json: any): CommunityLeaveModel {
    return CommunityLeaveModelFromJSONTyped(json, false);
}

export function CommunityLeaveModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityLeaveModel {
    if (json == null) {
        return json;
    }
    return {
        
        'memberUserIds': json['memberUserIds'] == null ? undefined : json['memberUserIds'],
    };
}

export function CommunityLeaveModelToJSON(value?: CommunityLeaveModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberUserIds': value['memberUserIds'],
    };
}

