/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { CommunityMemberResponseModel } from './CommunityMemberResponseModel';
import {
    CommunityMemberResponseModelFromJSON,
    CommunityMemberResponseModelFromJSONTyped,
    CommunityMemberResponseModelToJSON,
} from './CommunityMemberResponseModel';

/**
 * 
 * @export
 * @interface CommunityResponseModel
 */
export interface CommunityResponseModel {
    /**
     * Members. The community's members.
     * @type {Array<CommunityMemberResponseModel>}
     * @memberof CommunityResponseModel
     */
    members?: Array<CommunityMemberResponseModel>;
    /**
     * Name. The community's name.
     * @type {string}
     * @memberof CommunityResponseModel
     */
    name?: string;
    /**
     * Description. The community's description.
     * @type {string}
     * @memberof CommunityResponseModel
     */
    description?: string;
    /**
     * ID. The community's ID.
     * @type {number}
     * @memberof CommunityResponseModel
     */
    id?: number;
    /**
     * Member count. Number of members in the community.
     * @type {number}
     * @memberof CommunityResponseModel
     */
    memberCount?: number;
    /**
     * Tags. The community's tags.
     * @type {Array<TagSummaryResponseModel>}
     * @memberof CommunityResponseModel
     */
    tags?: Array<TagSummaryResponseModel>;
}

/**
 * Check if a given object implements the CommunityResponseModel interface.
 */
export function instanceOfCommunityResponseModel(value: object): value is CommunityResponseModel {
    return true;
}

export function CommunityResponseModelFromJSON(json: any): CommunityResponseModel {
    return CommunityResponseModelFromJSONTyped(json, false);
}

export function CommunityResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'members': json['members'] == null ? undefined : ((json['members'] as Array<any>).map(CommunityMemberResponseModelFromJSON)),
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagSummaryResponseModelFromJSON)),
    };
}

export function CommunityResponseModelToJSON(value?: CommunityResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'members': value['members'] == null ? undefined : ((value['members'] as Array<any>).map(CommunityMemberResponseModelToJSON)),
        'name': value['name'],
        'description': value['description'],
        'id': value['id'],
        'memberCount': value['memberCount'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagSummaryResponseModelToJSON)),
    };
}

