/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityMemberResponseModel
 */
export interface CommunityMemberResponseModel {
    /**
     * ID. The member's user ID.
     * @type {number}
     * @memberof CommunityMemberResponseModel
     */
    id?: number;
    /**
     * Name. The member's name.
     * @type {string}
     * @memberof CommunityMemberResponseModel
     */
    name?: string;
    /**
     * Member since. The date and time the member joined the community.
     * @type {Date}
     * @memberof CommunityMemberResponseModel
     */
    memberSince?: Date;
    /**
     * Is SME. Returns true if the member is a SME (subject matter expert) for one or more of the community's tags.
     * @type {boolean}
     * @memberof CommunityMemberResponseModel
     */
    isSme?: boolean;
}

/**
 * Check if a given object implements the CommunityMemberResponseModel interface.
 */
export function instanceOfCommunityMemberResponseModel(value: object): value is CommunityMemberResponseModel {
    return true;
}

export function CommunityMemberResponseModelFromJSON(json: any): CommunityMemberResponseModel {
    return CommunityMemberResponseModelFromJSONTyped(json, false);
}

export function CommunityMemberResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityMemberResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'memberSince': json['memberSince'] == null ? undefined : (new Date(json['memberSince'])),
        'isSme': json['isSme'] == null ? undefined : json['isSme'],
    };
}

export function CommunityMemberResponseModelToJSON(value?: CommunityMemberResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'memberSince': value['memberSince'] == null ? undefined : ((value['memberSince']).toISOString()),
        'isSme': value['isSme'],
    };
}

