/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommentResponseModel
 */
export interface CommentResponseModel {
    /**
     * ID. The comment's unique identifier.
     * @type {number}
     * @memberof CommentResponseModel
     */
    id?: number;
    /**
     * Comment score. Calculated by subtracting the number of downvotes from the number of upvotes.
     * @type {number}
     * @memberof CommentResponseModel
     */
    score?: number;
    /**
     * Comment body. The written content of the comment.
     * @type {string}
     * @memberof CommentResponseModel
     */
    body?: string;
    /**
     * Comment owner. ID of the user that posted the comment.
     * @type {number}
     * @memberof CommentResponseModel
     */
    ownerUserId?: number | null;
    /**
     * Creation date. The date and time the question was created.
     * @type {Date}
     * @memberof CommentResponseModel
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the CommentResponseModel interface.
 */
export function instanceOfCommentResponseModel(value: object): value is CommentResponseModel {
    return true;
}

export function CommentResponseModelFromJSON(json: any): CommentResponseModel {
    return CommentResponseModelFromJSONTyped(json, false);
}

export function CommentResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommentResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'score': json['score'] == null ? undefined : json['score'],
        'body': json['body'] == null ? undefined : json['body'],
        'ownerUserId': json['ownerUserId'] == null ? undefined : json['ownerUserId'],
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

export function CommentResponseModelToJSON(value?: CommentResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'score': value['score'],
        'body': value['body'],
        'ownerUserId': value['ownerUserId'],
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

