/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Communities sort parameter
 * @export
 */
export const CommunitySortParameter = {
    Name: 'name',
    Size: 'size'
} as const;
export type CommunitySortParameter = typeof CommunitySortParameter[keyof typeof CommunitySortParameter];


export function instanceOfCommunitySortParameter(value: any): boolean {
    for (const key in CommunitySortParameter) {
        if (Object.prototype.hasOwnProperty.call(CommunitySortParameter, key)) {
            if (CommunitySortParameter[key as keyof typeof CommunitySortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function CommunitySortParameterFromJSON(json: any): CommunitySortParameter {
    return CommunitySortParameterFromJSONTyped(json, false);
}

export function CommunitySortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunitySortParameter {
    return json as CommunitySortParameter;
}

export function CommunitySortParameterToJSON(value?: CommunitySortParameter | null): any {
    return value as any;
}

