/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommunityJoinModel
 */
export interface CommunityJoinModel {
    /**
     * Member User IDs. The identity of users who will join this community
     * @type {Array<number>}
     * @memberof CommunityJoinModel
     */
    memberUserIds?: Array<number>;
}

/**
 * Check if a given object implements the CommunityJoinModel interface.
 */
export function instanceOfCommunityJoinModel(value: object): value is CommunityJoinModel {
    return true;
}

export function CommunityJoinModelFromJSON(json: any): CommunityJoinModel {
    return CommunityJoinModelFromJSONTyped(json, false);
}

export function CommunityJoinModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommunityJoinModel {
    if (json == null) {
        return json;
    }
    return {
        
        'memberUserIds': json['memberUserIds'] == null ? undefined : json['memberUserIds'],
    };
}

export function CommunityJoinModelToJSON(value?: CommunityJoinModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'memberUserIds': value['memberUserIds'],
    };
}

