/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface EditCollectionRequestModel
 */
export interface EditCollectionRequestModel {
    /**
     * Owner ID. The ID of the user who has ownership of the collection.
     * @type {number}
     * @memberof EditCollectionRequestModel
     */
    ownerId?: number | null;
    /**
     * Title. A brief title to distinguish the collection and its contents.
     * @type {string}
     * @memberof EditCollectionRequestModel
     */
    title?: string;
    /**
     * Description. A detailed description of what the collection contains. Supports Markdown.
     * @type {string}
     * @memberof EditCollectionRequestModel
     */
    description?: string;
    /**
     * Editor user IDs. The IDs of users who can modify this collection.
     * @type {Array<number>}
     * @memberof EditCollectionRequestModel
     */
    editorUserIds?: Array<number>;
    /**
     * Editor user group IDs. The IDs of user groups whose members can modify this collection.
     * @type {Array<number>}
     * @memberof EditCollectionRequestModel
     */
    editorUserGroupIds?: Array<number>;
    /**
     * Content IDs. The IDs of questions and/or articles that this collection contains, in order.
     * @type {Array<number>}
     * @memberof EditCollectionRequestModel
     */
    contentIds?: Array<number>;
}

/**
 * Check if a given object implements the EditCollectionRequestModel interface.
 */
export function instanceOfEditCollectionRequestModel(value: object): value is EditCollectionRequestModel {
    return true;
}

export function EditCollectionRequestModelFromJSON(json: any): EditCollectionRequestModel {
    return EditCollectionRequestModelFromJSONTyped(json, false);
}

export function EditCollectionRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): EditCollectionRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'ownerId': json['ownerId'] == null ? undefined : json['ownerId'],
        'title': json['title'] == null ? undefined : json['title'],
        'description': json['description'] == null ? undefined : json['description'],
        'editorUserIds': json['editorUserIds'] == null ? undefined : json['editorUserIds'],
        'editorUserGroupIds': json['editorUserGroupIds'] == null ? undefined : json['editorUserGroupIds'],
        'contentIds': json['contentIds'] == null ? undefined : json['contentIds'],
    };
}

export function EditCollectionRequestModelToJSON(value?: EditCollectionRequestModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'ownerId': value['ownerId'],
        'title': value['title'],
        'description': value['description'],
        'editorUserIds': value['editorUserIds'],
        'editorUserGroupIds': value['editorUserGroupIds'],
        'contentIds': value['contentIds'],
    };
}

