/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Linked or related questions sort parameter
 * @export
 */
export const LinkedOrRelatedQuestionsSortParameter = {
    Hot: 'hot',
    Creation: 'creation',
    Activity: 'activity',
    Score: 'score'
} as const;
export type LinkedOrRelatedQuestionsSortParameter = typeof LinkedOrRelatedQuestionsSortParameter[keyof typeof LinkedOrRelatedQuestionsSortParameter];


export function instanceOfLinkedOrRelatedQuestionsSortParameter(value: any): boolean {
    for (const key in LinkedOrRelatedQuestionsSortParameter) {
        if (Object.prototype.hasOwnProperty.call(LinkedOrRelatedQuestionsSortParameter, key)) {
            if (LinkedOrRelatedQuestionsSortParameter[key as keyof typeof LinkedOrRelatedQuestionsSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LinkedOrRelatedQuestionsSortParameterFromJSON(json: any): LinkedOrRelatedQuestionsSortParameter {
    return LinkedOrRelatedQuestionsSortParameterFromJSONTyped(json, false);
}

export function LinkedOrRelatedQuestionsSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkedOrRelatedQuestionsSortParameter {
    return json as LinkedOrRelatedQuestionsSortParameter;
}

export function LinkedOrRelatedQuestionsSortParameterToJSON(value?: LinkedOrRelatedQuestionsSortParameter | null): any {
    return value as any;
}

