/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Manage users sort parameter
 * @export
 */
export const ManageUsersSortParameter = {
    Id: 'id',
    Name: 'name',
    Email: 'email',
    LastAccessDate: 'lastAccessDate'
} as const;
export type ManageUsersSortParameter = typeof ManageUsersSortParameter[keyof typeof ManageUsersSortParameter];


export function instanceOfManageUsersSortParameter(value: any): boolean {
    for (const key in ManageUsersSortParameter) {
        if (Object.prototype.hasOwnProperty.call(ManageUsersSortParameter, key)) {
            if (ManageUsersSortParameter[key as keyof typeof ManageUsersSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function ManageUsersSortParameterFromJSON(json: any): ManageUsersSortParameter {
    return ManageUsersSortParameterFromJSONTyped(json, false);
}

export function ManageUsersSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): ManageUsersSortParameter {
    return json as ManageUsersSortParameter;
}

export function ManageUsersSortParameterToJSON(value?: ManageUsersSortParameter | null): any {
    return value as any;
}

