/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MentionedUserResponseModel
 */
export interface MentionedUserResponseModel {
    /**
     * ID. The ID of the user mentioned in the question.
     * @type {number}
     * @memberof MentionedUserResponseModel
     */
    id?: number;
    /**
     * Name. The name of the user mentioned in the question.
     * @type {string}
     * @memberof MentionedUserResponseModel
     */
    name?: string;
}

/**
 * Check if a given object implements the MentionedUserResponseModel interface.
 */
export function instanceOfMentionedUserResponseModel(value: object): value is MentionedUserResponseModel {
    return true;
}

export function MentionedUserResponseModelFromJSON(json: any): MentionedUserResponseModel {
    return MentionedUserResponseModelFromJSONTyped(json, false);
}

export function MentionedUserResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionedUserResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function MentionedUserResponseModelToJSON(value?: MentionedUserResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
    };
}

