/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MentionedUserGroupResponseModel
 */
export interface MentionedUserGroupResponseModel {
    /**
     * ID. The ID of user group mentioned in the question.
     * @type {number}
     * @memberof MentionedUserGroupResponseModel
     */
    id?: number;
    /**
     * Name. The name of user group mentioned in the question.
     * @type {string}
     * @memberof MentionedUserGroupResponseModel
     */
    name?: string;
    /**
     * Member count. The number of members in the group mentioned in the question.
     * @type {number}
     * @memberof MentionedUserGroupResponseModel
     */
    memberCount?: number;
}

/**
 * Check if a given object implements the MentionedUserGroupResponseModel interface.
 */
export function instanceOfMentionedUserGroupResponseModel(value: object): value is MentionedUserGroupResponseModel {
    return true;
}

export function MentionedUserGroupResponseModelFromJSON(json: any): MentionedUserGroupResponseModel {
    return MentionedUserGroupResponseModelFromJSONTyped(json, false);
}

export function MentionedUserGroupResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): MentionedUserGroupResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'memberCount': json['memberCount'] == null ? undefined : json['memberCount'],
    };
}

export function MentionedUserGroupResponseModelToJSON(value?: MentionedUserGroupResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'memberCount': value['memberCount'],
    };
}

