/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UsersSortParameter } from './UsersSortParameter';
import {
    UsersSortParameterFromJSON,
    UsersSortParameterFromJSONTyped,
    UsersSortParameterToJSON,
} from './UsersSortParameter';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';
import type { UserResponseModel } from './UserResponseModel';
import {
    UserResponseModelFromJSON,
    UserResponseModelFromJSONTyped,
    UserResponseModelToJSON,
} from './UserResponseModel';

/**
 * 
 * @export
 * @interface PaginatedUsers
 */
export interface PaginatedUsers {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedUsers
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedUsers
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedUsers
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedUsers
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {UsersSortParameter}
     * @memberof PaginatedUsers
     */
    sort?: UsersSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedUsers
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<UserResponseModel>}
     * @memberof PaginatedUsers
     */
    readonly items?: Array<UserResponseModel>;
}



/**
 * Check if a given object implements the PaginatedUsers interface.
 */
export function instanceOfPaginatedUsers(value: object): value is PaginatedUsers {
    return true;
}

export function PaginatedUsersFromJSON(json: any): PaginatedUsers {
    return PaginatedUsersFromJSONTyped(json, false);
}

export function PaginatedUsersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUsers {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : UsersSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(UserResponseModelFromJSON)),
    };
}

export function PaginatedUsersToJSON(value?: Omit<PaginatedUsers, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': UsersSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

