/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupResponseModel } from './UserGroupResponseModel';
import {
    UserGroupResponseModelFromJSON,
    UserGroupResponseModelFromJSONTyped,
    UserGroupResponseModelToJSON,
} from './UserGroupResponseModel';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';
import type { UserGroupsSortParameter } from './UserGroupsSortParameter';
import {
    UserGroupsSortParameterFromJSON,
    UserGroupsSortParameterFromJSONTyped,
    UserGroupsSortParameterToJSON,
} from './UserGroupsSortParameter';

/**
 * 
 * @export
 * @interface PaginatedUserGroups
 */
export interface PaginatedUserGroups {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedUserGroups
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedUserGroups
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedUserGroups
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedUserGroups
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {UserGroupsSortParameter}
     * @memberof PaginatedUserGroups
     */
    sort?: UserGroupsSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedUserGroups
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<UserGroupResponseModel>}
     * @memberof PaginatedUserGroups
     */
    readonly items?: Array<UserGroupResponseModel>;
}



/**
 * Check if a given object implements the PaginatedUserGroups interface.
 */
export function instanceOfPaginatedUserGroups(value: object): value is PaginatedUserGroups {
    return true;
}

export function PaginatedUserGroupsFromJSON(json: any): PaginatedUserGroups {
    return PaginatedUserGroupsFromJSONTyped(json, false);
}

export function PaginatedUserGroupsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedUserGroups {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : UserGroupsSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(UserGroupResponseModelFromJSON)),
    };
}

export function PaginatedUserGroupsToJSON(value?: Omit<PaginatedUserGroups, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': UserGroupsSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

