/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AnswerSummaryResponseModel } from './AnswerSummaryResponseModel';
import {
    AnswerSummaryResponseModelFromJSON,
    AnswerSummaryResponseModelFromJSONTyped,
    AnswerSummaryResponseModelToJSON,
} from './AnswerSummaryResponseModel';
import type { AnswersSortParameter } from './AnswersSortParameter';
import {
    AnswersSortParameterFromJSON,
    AnswersSortParameterFromJSONTyped,
    AnswersSortParameterToJSON,
} from './AnswersSortParameter';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';

/**
 * 
 * @export
 * @interface PaginatedAnswers
 */
export interface PaginatedAnswers {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedAnswers
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedAnswers
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedAnswers
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedAnswers
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {AnswersSortParameter}
     * @memberof PaginatedAnswers
     */
    sort?: AnswersSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedAnswers
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<AnswerSummaryResponseModel>}
     * @memberof PaginatedAnswers
     */
    readonly items?: Array<AnswerSummaryResponseModel>;
}



/**
 * Check if a given object implements the PaginatedAnswers interface.
 */
export function instanceOfPaginatedAnswers(value: object): value is PaginatedAnswers {
    return true;
}

export function PaginatedAnswersFromJSON(json: any): PaginatedAnswers {
    return PaginatedAnswersFromJSONTyped(json, false);
}

export function PaginatedAnswersFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAnswers {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : AnswersSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(AnswerSummaryResponseModelFromJSON)),
    };
}

export function PaginatedAnswersToJSON(value?: Omit<PaginatedAnswers, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': AnswersSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

