/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CommunitySummaryResponseModel } from './CommunitySummaryResponseModel';
import {
    CommunitySummaryResponseModelFromJSON,
    CommunitySummaryResponseModelFromJSONTyped,
    CommunitySummaryResponseModelToJSON,
} from './CommunitySummaryResponseModel';
import type { CommunitySortParameter } from './CommunitySortParameter';
import {
    CommunitySortParameterFromJSON,
    CommunitySortParameterFromJSONTyped,
    CommunitySortParameterToJSON,
} from './CommunitySortParameter';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';

/**
 * 
 * @export
 * @interface PaginatedCommunities
 */
export interface PaginatedCommunities {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedCommunities
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedCommunities
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedCommunities
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedCommunities
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {CommunitySortParameter}
     * @memberof PaginatedCommunities
     */
    sort?: CommunitySortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedCommunities
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<CommunitySummaryResponseModel>}
     * @memberof PaginatedCommunities
     */
    readonly items?: Array<CommunitySummaryResponseModel>;
}



/**
 * Check if a given object implements the PaginatedCommunities interface.
 */
export function instanceOfPaginatedCommunities(value: object): value is PaginatedCommunities {
    return true;
}

export function PaginatedCommunitiesFromJSON(json: any): PaginatedCommunities {
    return PaginatedCommunitiesFromJSONTyped(json, false);
}

export function PaginatedCommunitiesFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCommunities {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : CommunitySortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CommunitySummaryResponseModelFromJSON)),
    };
}

export function PaginatedCommunitiesToJSON(value?: Omit<PaginatedCommunities, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': CommunitySortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

