/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';
import type { TagsSortParameter } from './TagsSortParameter';
import {
    TagsSortParameterFromJSON,
    TagsSortParameterFromJSONTyped,
    TagsSortParameterToJSON,
} from './TagsSortParameter';

/**
 * 
 * @export
 * @interface PaginatedTags
 */
export interface PaginatedTags {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedTags
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedTags
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedTags
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedTags
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {TagsSortParameter}
     * @memberof PaginatedTags
     */
    sort?: TagsSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedTags
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<TagSummaryResponseModel>}
     * @memberof PaginatedTags
     */
    readonly items?: Array<TagSummaryResponseModel>;
}



/**
 * Check if a given object implements the PaginatedTags interface.
 */
export function instanceOfPaginatedTags(value: object): value is PaginatedTags {
    return true;
}

export function PaginatedTagsFromJSON(json: any): PaginatedTags {
    return PaginatedTagsFromJSONTyped(json, false);
}

export function PaginatedTagsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedTags {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : TagsSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(TagSummaryResponseModelFromJSON)),
    };
}

export function PaginatedTagsToJSON(value?: Omit<PaginatedTags, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': TagsSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

