/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { AnswerSearchResultModel } from './AnswerSearchResultModel';
import {
    instanceOfAnswerSearchResultModel,
    AnswerSearchResultModelFromJSON,
    AnswerSearchResultModelFromJSONTyped,
    AnswerSearchResultModelToJSON,
} from './AnswerSearchResultModel';
import type { ArticleSearchResultModel } from './ArticleSearchResultModel';
import {
    instanceOfArticleSearchResultModel,
    ArticleSearchResultModelFromJSON,
    ArticleSearchResultModelFromJSONTyped,
    ArticleSearchResultModelToJSON,
} from './ArticleSearchResultModel';
import type { QuestionSearchResultModel } from './QuestionSearchResultModel';
import {
    instanceOfQuestionSearchResultModel,
    QuestionSearchResultModelFromJSON,
    QuestionSearchResultModelFromJSONTyped,
    QuestionSearchResultModelToJSON,
} from './QuestionSearchResultModel';

/**
 * @type PaginatedSearchResultsItemsInner
 * 
 * @export
 */
export type PaginatedSearchResultsItemsInner = AnswerSearchResultModel | ArticleSearchResultModel | QuestionSearchResultModel;

export function PaginatedSearchResultsItemsInnerFromJSON(json: any): PaginatedSearchResultsItemsInner {
    return PaginatedSearchResultsItemsInnerFromJSONTyped(json, false);
}

export function PaginatedSearchResultsItemsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedSearchResultsItemsInner {
    if (json == null) {
        return json;
    }
    if (instanceOfAnswerSearchResultModel(json)) {
        return AnswerSearchResultModelFromJSONTyped(json, true);
    }
    if (instanceOfArticleSearchResultModel(json)) {
        return ArticleSearchResultModelFromJSONTyped(json, true);
    }
    if (instanceOfQuestionSearchResultModel(json)) {
        return QuestionSearchResultModelFromJSONTyped(json, true);
    }

    return {} as any;
}

export function PaginatedSearchResultsItemsInnerToJSON(value?: PaginatedSearchResultsItemsInner | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfAnswerSearchResultModel(value)) {
        return AnswerSearchResultModelToJSON(value as AnswerSearchResultModel);
    }
    if (instanceOfArticleSearchResultModel(value)) {
        return ArticleSearchResultModelToJSON(value as ArticleSearchResultModel);
    }
    if (instanceOfQuestionSearchResultModel(value)) {
        return QuestionSearchResultModelToJSON(value as QuestionSearchResultModel);
    }

    return {};
}

