/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QuestionSummaryResponseModel } from './QuestionSummaryResponseModel';
import {
    QuestionSummaryResponseModelFromJSON,
    QuestionSummaryResponseModelFromJSONTyped,
    QuestionSummaryResponseModelToJSON,
} from './QuestionSummaryResponseModel';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';
import type { QuestionSortParameter } from './QuestionSortParameter';
import {
    QuestionSortParameterFromJSON,
    QuestionSortParameterFromJSONTyped,
    QuestionSortParameterToJSON,
} from './QuestionSortParameter';

/**
 * 
 * @export
 * @interface PaginatedQuestions
 */
export interface PaginatedQuestions {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedQuestions
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedQuestions
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedQuestions
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedQuestions
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {QuestionSortParameter}
     * @memberof PaginatedQuestions
     */
    sort?: QuestionSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedQuestions
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<QuestionSummaryResponseModel>}
     * @memberof PaginatedQuestions
     */
    readonly items?: Array<QuestionSummaryResponseModel>;
}



/**
 * Check if a given object implements the PaginatedQuestions interface.
 */
export function instanceOfPaginatedQuestions(value: object): value is PaginatedQuestions {
    return true;
}

export function PaginatedQuestionsFromJSON(json: any): PaginatedQuestions {
    return PaginatedQuestionsFromJSONTyped(json, false);
}

export function PaginatedQuestionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedQuestions {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : QuestionSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(QuestionSummaryResponseModelFromJSON)),
    };
}

export function PaginatedQuestionsToJSON(value?: Omit<PaginatedQuestions, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': QuestionSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

