/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { CollectionsSummaryResponseModel } from './CollectionsSummaryResponseModel';
import {
    CollectionsSummaryResponseModelFromJSON,
    CollectionsSummaryResponseModelFromJSONTyped,
    CollectionsSummaryResponseModelToJSON,
} from './CollectionsSummaryResponseModel';
import type { SortOrder } from './SortOrder';
import {
    SortOrderFromJSON,
    SortOrderFromJSONTyped,
    SortOrderToJSON,
} from './SortOrder';
import type { CollectionsSortParameter } from './CollectionsSortParameter';
import {
    CollectionsSortParameterFromJSON,
    CollectionsSortParameterFromJSONTyped,
    CollectionsSortParameterToJSON,
} from './CollectionsSortParameter';

/**
 * 
 * @export
 * @interface PaginatedCollections
 */
export interface PaginatedCollections {
    /**
     * Total count. The total number of records found.
     * @type {number}
     * @memberof PaginatedCollections
     */
    readonly totalCount?: number;
    /**
     * Page size. The number of records to retrieve per page.
     * @type {number}
     * @memberof PaginatedCollections
     */
    readonly pageSize?: number;
    /**
     * Page. The number of the current page.
     * @type {number}
     * @memberof PaginatedCollections
     */
    readonly page?: number;
    /**
     * Total pages. The total number of pages available.
     * @type {number}
     * @memberof PaginatedCollections
     */
    readonly totalPages?: number;
    /**
     * 
     * @type {CollectionsSortParameter}
     * @memberof PaginatedCollections
     */
    sort?: CollectionsSortParameter;
    /**
     * 
     * @type {SortOrder}
     * @memberof PaginatedCollections
     */
    order?: SortOrder;
    /**
     * 
     * @type {Array<CollectionsSummaryResponseModel>}
     * @memberof PaginatedCollections
     */
    readonly items?: Array<CollectionsSummaryResponseModel>;
}



/**
 * Check if a given object implements the PaginatedCollections interface.
 */
export function instanceOfPaginatedCollections(value: object): value is PaginatedCollections {
    return true;
}

export function PaginatedCollectionsFromJSON(json: any): PaginatedCollections {
    return PaginatedCollectionsFromJSONTyped(json, false);
}

export function PaginatedCollectionsFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedCollections {
    if (json == null) {
        return json;
    }
    return {
        
        'totalCount': json['totalCount'] == null ? undefined : json['totalCount'],
        'pageSize': json['pageSize'] == null ? undefined : json['pageSize'],
        'page': json['page'] == null ? undefined : json['page'],
        'totalPages': json['totalPages'] == null ? undefined : json['totalPages'],
        'sort': json['sort'] == null ? undefined : CollectionsSortParameterFromJSON(json['sort']),
        'order': json['order'] == null ? undefined : SortOrderFromJSON(json['order']),
        'items': json['items'] == null ? undefined : ((json['items'] as Array<any>).map(CollectionsSummaryResponseModelFromJSON)),
    };
}

export function PaginatedCollectionsToJSON(value?: Omit<PaginatedCollections, 'totalCount'|'pageSize'|'page'|'totalPages'|'items'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'sort': CollectionsSortParameterToJSON(value['sort']),
        'order': SortOrderToJSON(value['order']),
    };
}

