/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QuestionRequestModel
 */
export interface QuestionRequestModel {
    /**
     * Question title. The actual question, stated briefly in one sentence.
     * @type {string}
     * @memberof QuestionRequestModel
     */
    title: string;
    /**
     * Body. Additional details to clarify the question.
     * @type {string}
     * @memberof QuestionRequestModel
     */
    body: string;
    /**
     * Tags. Tags associated with the question.
     * @type {Array<string>}
     * @memberof QuestionRequestModel
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the QuestionRequestModel interface.
 */
export function instanceOfQuestionRequestModel(value: object): value is QuestionRequestModel {
    if (!('title' in value) || value['title'] === undefined) return false;
    if (!('body' in value) || value['body'] === undefined) return false;
    if (!('tags' in value) || value['tags'] === undefined) return false;
    return true;
}

export function QuestionRequestModelFromJSON(json: any): QuestionRequestModel {
    return QuestionRequestModelFromJSONTyped(json, false);
}

export function QuestionRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'],
        'body': json['body'],
        'tags': json['tags'],
    };
}

export function QuestionRequestModelToJSON(value?: QuestionRequestModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'body': value['body'],
        'tags': value['tags'],
    };
}

