/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Questions sort parameter
 * @export
 */
export const QuestionSortParameter = {
    Activity: 'activity',
    Creation: 'creation',
    Score: 'score'
} as const;
export type QuestionSortParameter = typeof QuestionSortParameter[keyof typeof QuestionSortParameter];


export function instanceOfQuestionSortParameter(value: any): boolean {
    for (const key in QuestionSortParameter) {
        if (Object.prototype.hasOwnProperty.call(QuestionSortParameter, key)) {
            if (QuestionSortParameter[key as keyof typeof QuestionSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QuestionSortParameterFromJSON(json: any): QuestionSortParameter {
    return QuestionSortParameterFromJSONTyped(json, false);
}

export function QuestionSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): QuestionSortParameter {
    return json as QuestionSortParameter;
}

export function QuestionSortParameterToJSON(value?: QuestionSortParameter | null): any {
    return value as any;
}

