/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * JSON representation of a question request
 */
export type QuestionRequestModelJson = {
    title: string;
    body: string;
    tags: string[];
}

/**
 * 
 * @export
 * @interface QuestionRequestModel
 */
export interface QuestionRequestModel {
    /**
     * Question title. The actual question, stated briefly in one sentence.
     * @type {string}
     * @memberof QuestionRequestModel
     */
    title: string;
    /**
     * Body. Additional details to clarify the question.
     * @type {string}
     * @memberof QuestionRequestModel
     */
    body: string;
    /**
     * Tags. Tags associated with the question.
     * @type {Array<string>}
     * @memberof QuestionRequestModel
     */
    tags: Array<string>;
}

/**
 * Check if a given object implements the QuestionRequestModel interface.
 */
export function instanceOfQuestionRequestModel(value: unknown): value is QuestionRequestModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<QuestionRequestModel>;
    
    return typeof v.title === 'string' &&
           typeof v.body === 'string' &&
           Array.isArray(v.tags) &&
           v.tags.every(tag => typeof tag === 'string');
}

export function QuestionRequestModelFromJSON(json: QuestionRequestModelJson): QuestionRequestModel {
    return QuestionRequestModelFromJSONTyped(json, false);
}

export function QuestionRequestModelFromJSONTyped(
    json: QuestionRequestModelJson,
    ignoreDiscriminator: boolean
): QuestionRequestModel {
    if (!json) {
        throw new Error('QuestionRequestModel JSON cannot be null or undefined');
    }
    
    return {
        'title': json.title,
        'body': json.body,
        'tags': json.tags,
    };
}

export function QuestionRequestModelToJSON(value?: QuestionRequestModel | null): QuestionRequestModelJson | null {
    if (!value) {
        return null;
    }
    
    return {
        'title': value.title,
        'body': value.body,
        'tags': value.tags,
    };
}

