/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { TagSummaryResponseModel } from './TagSummaryResponseModel';
import {
    TagSummaryResponseModelFromJSON,
    TagSummaryResponseModelFromJSONTyped,
    TagSummaryResponseModelToJSON,
} from './TagSummaryResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface SearchResultModel
 */
export interface SearchResultModel {
    /**
     * 
     * @type {string}
     * @memberof SearchResultModel
     */
    title?: string;
    /**
     * 
     * @type {string}
     * @memberof SearchResultModel
     */
    snippet?: string;
    /**
     * 
     * @type {Array<TagSummaryResponseModel>}
     * @memberof SearchResultModel
     */
    tags?: Array<TagSummaryResponseModel>;
    /**
     * 
     * @type {UserSummaryResponseModel}
     * @memberof SearchResultModel
     */
    owner?: UserSummaryResponseModel;
    /**
     * 
     * @type {Date}
     * @memberof SearchResultModel
     */
    creationDate?: Date;
}

/**
 * Check if a given object implements the SearchResultModel interface.
 */
export function instanceOfSearchResultModel(value: object): value is SearchResultModel {
    return true;
}

export function SearchResultModelFromJSON(json: any): SearchResultModel {
    return SearchResultModelFromJSONTyped(json, false);
}

export function SearchResultModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SearchResultModel {
    if (json == null) {
        return json;
    }
    return {
        
        'title': json['title'] == null ? undefined : json['title'],
        'snippet': json['snippet'] == null ? undefined : json['snippet'],
        'tags': json['tags'] == null ? undefined : ((json['tags'] as Array<any>).map(TagSummaryResponseModelFromJSON)),
        'owner': json['owner'] == null ? undefined : UserSummaryResponseModelFromJSON(json['owner']),
        'creationDate': json['creationDate'] == null ? undefined : (new Date(json['creationDate'])),
    };
}

export function SearchResultModelToJSON(value?: SearchResultModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'title': value['title'],
        'snippet': value['snippet'],
        'tags': value['tags'] == null ? undefined : ((value['tags'] as Array<any>).map(TagSummaryResponseModelToJSON)),
        'owner': UserSummaryResponseModelToJSON(value['owner']),
        'creationDate': value['creationDate'] == null ? undefined : ((value['creationDate']).toISOString()),
    };
}

