/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Sort Order
 * @export
 */
export const SortOrder = {
    Asc: 'asc',
    Desc: 'desc'
} as const;
export type SortOrder = typeof SortOrder[keyof typeof SortOrder];

export function instanceOfSortOrder(value: unknown): value is SortOrder {
    return typeof value === 'string' && Object.values(SortOrder).includes(value as SortOrder);
}

export function SortOrderFromJSON(json: unknown): SortOrder {
    return SortOrderFromJSONTyped(json, false);
}

export function SortOrderFromJSONTyped(json: unknown, ignoreDiscriminator: boolean): SortOrder {
    if (!instanceOfSortOrder(json)) {
        throw new Error('Invalid SortOrder value');
    }
    return json;
}

export function SortOrderToJSON(value?: SortOrder | null): SortOrder | null {
    return value ?? null;
}

