/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserGroupResponseModel } from './UserGroupResponseModel';
import {
    UserGroupResponseModelFromJSON,
    UserGroupResponseModelFromJSONTyped,
    UserGroupResponseModelToJSON,
} from './UserGroupResponseModel';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface SubjectMatterExpertResponseModel
 */
export interface SubjectMatterExpertResponseModel {
    /**
     * Users. The users identified as subject matter experts for the specified tag.
     * @type {Array<UserSummaryResponseModel>}
     * @memberof SubjectMatterExpertResponseModel
     */
    users?: Array<UserSummaryResponseModel>;
    /**
     * User groups. The user groups identified as subject matter experts for the specified tag.
     * @type {Array<UserGroupResponseModel>}
     * @memberof SubjectMatterExpertResponseModel
     */
    userGroups?: Array<UserGroupResponseModel>;
}

/**
 * Check if a given object implements the SubjectMatterExpertResponseModel interface.
 */
export function instanceOfSubjectMatterExpertResponseModel(value: object): value is SubjectMatterExpertResponseModel {
    return true;
}

export function SubjectMatterExpertResponseModelFromJSON(json: any): SubjectMatterExpertResponseModel {
    return SubjectMatterExpertResponseModelFromJSONTyped(json, false);
}

export function SubjectMatterExpertResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectMatterExpertResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserSummaryResponseModelFromJSON)),
        'userGroups': json['userGroups'] == null ? undefined : ((json['userGroups'] as Array<any>).map(UserGroupResponseModelFromJSON)),
    };
}

export function SubjectMatterExpertResponseModelToJSON(value?: SubjectMatterExpertResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserSummaryResponseModelToJSON)),
        'userGroups': value['userGroups'] == null ? undefined : ((value['userGroups'] as Array<any>).map(UserGroupResponseModelToJSON)),
    };
}

