/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SubjectMatterExpertRequestModel
 */
export interface SubjectMatterExpertRequestModel {
    /**
     * 
     * @type {Array<number>}
     * @memberof SubjectMatterExpertRequestModel
     */
    userIds?: Array<number>;
    /**
     * 
     * @type {Array<number>}
     * @memberof SubjectMatterExpertRequestModel
     */
    userGroupIds?: Array<number>;
}

/**
 * Check if a given object implements the SubjectMatterExpertRequestModel interface.
 */
export function instanceOfSubjectMatterExpertRequestModel(value: object): value is SubjectMatterExpertRequestModel {
    return true;
}

export function SubjectMatterExpertRequestModelFromJSON(json: any): SubjectMatterExpertRequestModel {
    return SubjectMatterExpertRequestModelFromJSONTyped(json, false);
}

export function SubjectMatterExpertRequestModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): SubjectMatterExpertRequestModel {
    if (json == null) {
        return json;
    }
    return {
        
        'userIds': json['userIds'] == null ? undefined : json['userIds'],
        'userGroupIds': json['userGroupIds'] == null ? undefined : json['userGroupIds'],
    };
}

export function SubjectMatterExpertRequestModelToJSON(value?: SubjectMatterExpertRequestModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'userIds': value['userIds'],
        'userGroupIds': value['userGroupIds'],
    };
}

