/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Tags sort parameter
 * @export
 */
export const TagsSortParameter = {
    Name: 'name',
    PostCount: 'postCount',
    CreationDate: 'creationDate'
} as const;
export type TagsSortParameter = typeof TagsSortParameter[keyof typeof TagsSortParameter];


export function instanceOfTagsSortParameter(value: any): boolean {
    for (const key in TagsSortParameter) {
        if (Object.prototype.hasOwnProperty.call(TagsSortParameter, key)) {
            if (TagsSortParameter[key as keyof typeof TagsSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TagsSortParameterFromJSON(json: any): TagsSortParameter {
    return TagsSortParameterFromJSONTyped(json, false);
}

export function TagsSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): TagsSortParameter {
    return json as TagsSortParameter;
}

export function TagsSortParameterToJSON(value?: TagsSortParameter | null): any {
    return value as any;
}

