/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserSummaryResponseModel } from './UserSummaryResponseModel';
import {
    UserSummaryResponseModelFromJSON,
    UserSummaryResponseModelFromJSONTyped,
    UserSummaryResponseModelToJSON,
} from './UserSummaryResponseModel';

/**
 * 
 * @export
 * @interface UserGroupResponseModel
 */
export interface UserGroupResponseModel {
    /**
     * ID. The user group's unique identifier.
     * @type {number}
     * @memberof UserGroupResponseModel
     */
    id?: number;
    /**
     * Name. The user group's name.
     * @type {string}
     * @memberof UserGroupResponseModel
     */
    name?: string;
    /**
     * Description. The user group's description.
     * @type {string}
     * @memberof UserGroupResponseModel
     */
    description?: string;
    /**
     * 
     * @type {Array<UserSummaryResponseModel>}
     * @memberof UserGroupResponseModel
     */
    users?: Array<UserSummaryResponseModel>;
}

/**
 * Check if a given object implements the UserGroupResponseModel interface.
 */
export function instanceOfUserGroupResponseModel(value: object): value is UserGroupResponseModel {
    return true;
}

export function UserGroupResponseModelFromJSON(json: any): UserGroupResponseModel {
    return UserGroupResponseModelFromJSONTyped(json, false);
}

export function UserGroupResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'users': json['users'] == null ? undefined : ((json['users'] as Array<any>).map(UserSummaryResponseModelFromJSON)),
    };
}

export function UserGroupResponseModelToJSON(value?: UserGroupResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'description': value['description'],
        'users': value['users'] == null ? undefined : ((value['users'] as Array<any>).map(UserSummaryResponseModelToJSON)),
    };
}

