/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSummaryResponseModel
 */
export interface UserSummaryResponseModel {
    /**
     * ID. The user's unique identifier on this site.
     * @type {number}
     * @memberof UserSummaryResponseModel
     */
    id?: number;
    /**
     * Account ID. The user's unique account identifier across all Stack Overflow sites.
     * @type {number}
     * @memberof UserSummaryResponseModel
     */
    accountId?: number | null;
    /**
     * Name. The user's name.
     * @type {string}
     * @memberof UserSummaryResponseModel
     */
    name?: string;
    /**
     * Avatar URL. The URL to the user's avatar (profile picture).
     * @type {string}
     * @memberof UserSummaryResponseModel
     */
    avatarUrl?: string;
    /**
     * Reputation. The user's numerical reputation.
     * @type {number}
     * @memberof UserSummaryResponseModel
     */
    reputation?: number;
    /**
     * Role. The user's role on the site.
     * @type {string}
     * @memberof UserSummaryResponseModel
     */
    role?: string;
}

/**
 * Check if a given object implements the UserSummaryResponseModel interface.
 */
export function instanceOfUserSummaryResponseModel(value: unknown): value is UserSummaryResponseModel {
    if (!value || typeof value !== 'object') {
        return false;
    }
    const obj = value as UserSummaryResponseModel;
    return (
        (obj.id === undefined || typeof obj.id === 'number') &&
        (obj.accountId === undefined || obj.accountId === null || typeof obj.accountId === 'number') &&
        (obj.name === undefined || typeof obj.name === 'string') &&
        (obj.avatarUrl === undefined || typeof obj.avatarUrl === 'string') &&
        (obj.reputation === undefined || typeof obj.reputation === 'number') &&
        (obj.role === undefined || typeof obj.role === 'string')
    );
}

export function UserSummaryResponseModelFromJSON(json: any): UserSummaryResponseModel {
    return UserSummaryResponseModelFromJSONTyped(json, false);
}

export function UserSummaryResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSummaryResponseModel {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'accountId': json['accountId'] == null ? undefined : json['accountId'],
        'name': json['name'] == null ? undefined : json['name'],
        'avatarUrl': json['avatarUrl'] == null ? undefined : json['avatarUrl'],
        'reputation': json['reputation'] == null ? undefined : json['reputation'],
        'role': json['role'] == null ? undefined : json['role'],
    };
}

export function UserSummaryResponseModelToJSON(value?: UserSummaryResponseModel | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'accountId': value['accountId'],
        'name': value['name'],
        'avatarUrl': value['avatarUrl'],
        'reputation': value['reputation'],
        'role': value['role'],
    };
}

