/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * JSON representation of a user group request
 */
export type UserGroupRequestModelJson = {
    name: string;
    description?: string;
    userIds?: number[];
}

/**
 * 
 * @export
 * @interface UserGroupRequestModel
 */
export interface UserGroupRequestModel {
    /**
     * The user group's name.
     * @type {string}
     * @memberof UserGroupRequestModel
     */
    name: string;
    /**
     * The user group's description.
     * @type {string}
     * @memberof UserGroupRequestModel
     */
    description?: string;
    /**
     * User IDs.
     * @type {Array<number>}
     * @memberof UserGroupRequestModel
     */
    userIds?: Array<number>;
}

/**
 * Check if a given object implements the UserGroupRequestModel interface.
 */
export function instanceOfUserGroupRequestModel(value: unknown): value is UserGroupRequestModel {
    if (!value || typeof value !== 'object') return false;
    const v = value as Partial<UserGroupRequestModel>;
    
    return typeof v.name === 'string' &&
           (v.description === undefined || typeof v.description === 'string') &&
           (v.userIds === undefined || (Array.isArray(v.userIds) && v.userIds.every(id => typeof id === 'number')));
}

export function UserGroupRequestModelFromJSON(json: UserGroupRequestModelJson): UserGroupRequestModel {
    return UserGroupRequestModelFromJSONTyped(json, false);
}

export function UserGroupRequestModelFromJSONTyped(
    json: UserGroupRequestModelJson,
    ignoreDiscriminator: boolean
): UserGroupRequestModel {
    if (!json) {
        throw new Error('UserGroupRequestModel JSON cannot be null or undefined');
    }
    
    return {
        'name': json.name,
        'description': json.description,
        'userIds': json.userIds,
    };
}

export function UserGroupRequestModelToJSON(value?: UserGroupRequestModel | null): UserGroupRequestModelJson | null {
    if (!value) {
        return null;
    }
    
    return {
        'name': value.name,
        'description': value.description,
        'userIds': value.userIds,
    };
}

