/* tslint:disable */
/* eslint-disable */
/**
 * Stack Overflow for Teams API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * User groups sort parameter
 * @export
 */
export const UserGroupsSortParameter = {
    Name: 'name',
    Size: 'size'
} as const;
export type UserGroupsSortParameter = typeof UserGroupsSortParameter[keyof typeof UserGroupsSortParameter];


export function instanceOfUserGroupsSortParameter(value: any): boolean {
    for (const key in UserGroupsSortParameter) {
        if (Object.prototype.hasOwnProperty.call(UserGroupsSortParameter, key)) {
            if (UserGroupsSortParameter[key as keyof typeof UserGroupsSortParameter] === value) {
                return true;
            }
        }
    }
    return false;
}

export function UserGroupsSortParameterFromJSON(json: any): UserGroupsSortParameter {
    return UserGroupsSortParameterFromJSONTyped(json, false);
}

export function UserGroupsSortParameterFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserGroupsSortParameter {
    return json as UserGroupsSortParameter;
}

export function UserGroupsSortParameterToJSON(value?: UserGroupsSortParameter | null): any {
    return value as any;
}

